export const pricingPlans = [
    {
      title: "Business Websites",
      description: "Showcase your business info, services and contact details",
      originalPrice: "₦350K",
      discount: "25%",
      price: "₦200K",
      features: [
        "Custom responsive website (mobile & desktop friendly)",
        "Fast and Secure Hosting",
        "SEO-Optimized Delivery",
        "Domain Integration and Setup",
        "CTA for customer inquiries",
        "integration with social media pages",
        "Free maintenance & Support for 30 days",
      ],
      buttonText: "Get Started",
      renewalNote: "* Billed as ₦70,000 yearly (renewal)",
      message: "Hey there! I came across your website and I'm interested in your Business web development services. I'd love to learn more!",
    },
    {
      title: "E-commerce & Booking websites",
      description: "Includes everything in a business website plus online ordering, payments or booking functionality",
      originalPrice: "₦500K",
      discount: "17%",
      price: "₦450K",
      features: [
        "Online Store Setup with product or service listings",
        "Fast and Secure Hosting",
        "SEO-Optimized Delivery",
        "Domain Integration and Setup",
        "Secure Payment Gateway",
        "Cart and Checkout Process",
        "Appointment Booking Systems",
        "Order management and notifications",
        "Customer Login and account management",
        "Admin Dashboard",
        "CTA for customer inquiries",
        "integration with social media pages",
        "Free maintenance & Support for 30 days",
      ],
      buttonText: "Get Started",
      renewalNote: "* Billed as ₦100,000 yearly (renewal)",
      message: "Hey there! I came across your website and I'm interested in your e-commerce web development services. I'd love to learn more!",
    },
    {
      title: "Custom or Advanced websites",
      description: "For businesses that need more than a standard website, custom solutions with features like membership systems, dashboards, and integrations tailored to your needs.",
      features: [],
      buttonText: "Contact Us",
      message: "Hey there! I came across your website and I'm interested in your custom website development services. I'd love to learn more!",
    }
  ];

  export const globalPricingPlans = [
    {
      title: "Business Websites",
      description: "Showcase your business info, services and contact details",
      originalPrice: "$400",
      discount: "30%",
      price: "$300",
      features: [
        "Custom responsive website (mobile & desktop friendly)",
        "Fast and Secure Hosting",
        "SEO-Optimized Delivery",
        "Domain Integration and Setup",
        "CTA for customer inquiries",
        "integration with social media pages",
        "Free maintenance & Support for 30 days",
      ],
      buttonText: "Get Started",
      renewalNote: "* Billed as $100 yearly (renewal)",
      message: "Hey there! I came across your website and I'm interested in your Business web development services. I'd love to learn more!",
    },
    {
      title: "E-commerce & Booking websites",
      description: "Includes everything in a business website plus online ordering, payments or booking functionality",
      originalPrice: "$1000",
      discount: "20%",
      price: "$750",
      features: [
        "Online Store Setup with product or service listings",
        "Fast and Secure Hosting",
        "SEO-Optimized Delivery",
        "Domain Integration and Setup",
        "Secure Payment Gateway",
        "Cart and Checkout Process",
        "Appointment Booking Systems",
        "Order management and notifications",
        "Customer Login and account management",
        "Admin Dashboard",
        "CTA for customer inquiries",
        "integration with social media pages",
        "Free maintenance & Support for 30 days",
      ],
      buttonText: "Get Started",
      renewalNote: "* Billed as $170 yearly (renewal)",
      message: "Hey there! I came across your website and I'm interested in your e-commerce web development services. I'd love to learn more!",
    },
    {
      title: "Custom or Advanced websites",
      description: "For businesses that need more than a standard website, custom solutions with features like membership systems, dashboards, and integrations tailored to your needs.",
      features: [],
      buttonText: "Contact Us",
      message: "Hey there! I came across your website and I'm interested in your custom website development services. I'd love to learn more!",
    }
  ];