export const pricingPlans = [
    {
      title: "Business Websites",
      description: "Showcase your business info, services and contact details",
      originalPrice: "₦200K",
      discount: "50%",
      price: "₦100K",
      features: [
        "Custom responsive website (mobile & desktop friendly)",
        "Fast and Secure Hosting",
        "Domain Integration and Setup",
        "CTA for customer inquiries",
        "integration with social media pages",
        "Free maintenance & Support for one year",
      ],
      buttonText: "Get Started",
      renewalNote: "* Billed as ₦70,000 yearly (renewal)",
      message: "Hey there! I came across your website and I'm interested in your Business web development services. I'd love to learn more!",
    },
    {
      title: "E-commerce & Booking websites",
      description: "Includes everything in a business website plus online ordering, payments or booking functionality",
      originalPrice: "₦375K",
      discount: "47%",
      price: "₦200K",
      features: [
        "Online Store Setup with product or service listings",
        "Fast and Secure Hosting",
        "Domain Integration and Setup",
        "Secure Payment Gateway",
        "Cart and Checkout Process",
        "Appointment Booking Systems (for salons, hotels etc.)",
        "Order management and notifications",
        "Customer Login and account management if needed",
        "Admin Dashboard",
        "CTA for customer inquiries",
        "integration with social media pages",
        "Free maintenance & Support for one year",
      ],
      buttonText: "Get Started",
      renewalNote: "* Billed as ₦100,000 yearly (renewal)",
      message: "Hey there! I came across your website and I'm interested in your e-commerce web development services. I'd love to learn more!",
    },
    {
      title: "Custom or Advanced websites",
      description: "For businesses that need more than a standard website, custom solutions with features like membership systems, dashboards, and integrations tailored to your needs.",
      features: [],
      buttonText: "Contact Us",
      message: "Hey there! I came across your website and I'm interested in your custom website development services. I'd love to learn more!",
    }
  ];

  export const globalPricingPlans = [
    {
      title: "Business Websites",
      description: "Showcase your business info, services and contact details",
      originalPrice: "$250",
      discount: "50%",
      price: "$175",
      features: [
        "Custom responsive website (mobile & desktop friendly)",
        "Fast and Secure Hosting",
        "Domain Integration and Setup",
        "CTA for customer inquiries",
        "integration with social media pages",
        "Free maintenance & Support for one year",
      ],
      buttonText: "Get Started",
      renewalNote: "* Billed as $100 yearly (renewal)",
      message: "Hey there! I came across your website and I'm interested in your Business web development services. I'd love to learn more!",
    },
    {
      title: "E-commerce & Booking websites",
      description: "Includes everything in a business website plus online ordering, payments or booking functionality",
      originalPrice: "$475",
      discount: "47%",
      price: "$350",
      features: [
        "Online Store Setup with product or service listings",
        "Fast and Secure Hosting",
        "Domain Integration and Setup",
        "Secure Payment Gateway",
        "Cart and Checkout Process",
        "Appointment Booking Systems (for salons, hotels etc.)",
        "Order management and notifications",
        "Customer Login and account management if needed",
        "Admin Dashboard",
        "CTA for customer inquiries",
        "integration with social media pages",
        "Free maintenance & Support for one year",
      ],
      buttonText: "Get Started",
      renewalNote: "* Billed as $120 yearly (renewal)",
      message: "Hey there! I came across your website and I'm interested in your e-commerce web development services. I'd love to learn more!",
    },
    {
      title: "Custom or Advanced websites",
      description: "For businesses that need more than a standard website, custom solutions with features like membership systems, dashboards, and integrations tailored to your needs.",
      features: [],
      buttonText: "Contact Us",
      message: "Hey there! I came across your website and I'm interested in your custom website development services. I'd love to learn more!",
    }
  ];